// <auto-generated />
using System;
using Manutencao.Solicitacao.Infra.BancoDeDados.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Manutencao.Solicitacao.Infra.BancoDeDados.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Manutencao.Solicitacao.Dominio.SolicitacoesDeManutencao.SolicitacaoDeManutencao", b =>
                {
                    b.Property<string>("Identificador")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataDaSolicitacao");

                    b.Property<DateTime>("InicioDesejadoParaManutencao");

                    b.Property<string>("Justificativa");

                    b.Property<int>("StatusDaSolicitacao");

                    b.Property<int>("TipoDeSolicitacaoDeManutencao");

                    b.HasKey("Identificador");

                    b.ToTable("SolicitacaoDeManutecao");
                });

            modelBuilder.Entity("Manutencao.Solicitacao.Dominio.SolicitacoesDeManutencao.SolicitacaoDeManutencao", b =>
                {
                    b.OwnsOne("Manutencao.Solicitacao.Dominio.SolicitacoesDeManutencao.Contrato", "Contrato", b1 =>
                        {
                            b1.Property<string>("SolicitacaoDeManutencaoId");

                            b1.Property<string>("CnpjDaTerceirizada");

                            b1.Property<DateTime>("DataFinalDaVigencia");

                            b1.Property<string>("GestorDoContrato");

                            b1.Property<string>("NomeDaTerceirizada");

                            b1.Property<string>("Numero");

                            b1.HasKey("SolicitacaoDeManutencaoId");

                            b1.ToTable("SolicitacaoDeManutecao");

                            b1.HasOne("Manutencao.Solicitacao.Dominio.SolicitacoesDeManutencao.SolicitacaoDeManutencao")
                                .WithOne("Contrato")
                                .HasForeignKey("Manutencao.Solicitacao.Dominio.SolicitacoesDeManutencao.Contrato", "SolicitacaoDeManutencaoId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Manutencao.Solicitacao.Dominio.SolicitacoesDeManutencao.Solicitante", "Solicitante", b1 =>
                        {
                            b1.Property<string>("SolicitacaoDeManutencaoId");

                            b1.Property<int>("Identificador");

                            b1.Property<string>("Nome");

                            b1.HasKey("SolicitacaoDeManutencaoId");

                            b1.ToTable("SolicitacaoDeManutecao");

                            b1.HasOne("Manutencao.Solicitacao.Dominio.SolicitacoesDeManutencao.SolicitacaoDeManutencao")
                                .WithOne("Solicitante")
                                .HasForeignKey("Manutencao.Solicitacao.Dominio.SolicitacoesDeManutencao.Solicitante", "SolicitacaoDeManutencaoId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
